### ISSUE TITLE
Compatibility issue with Laravel 5.1

### ISSUE THREAD

**Issue by Prijink** [Dionera/laravel-beanstalkd-admin-ui#6]
URL` /beanstalkd/tubes` throws following error on Laravel 5.1.19. Method call flatmap in controller makes the issue.

**FatalThrowableError in TubesController.php line 41:**
Call to undefined method Illuminate\Support\Collection::flatMap()

in TubesController.php line 41
at TubesController->index()
at ControllerDispatcher->callWithinStack(object(TubesController), object(Route), object(Request), 'index') in ControllerDispatcher.php line 67
at ControllerDispatcher->dispatch(object(Route), object(Request), **'Dionera\BeanstalkdUI\Controllers\TubesController', 'index'**) in Route.php line 201

**Comment by ksassnowski** [comment]
Looks like `flatMap` got introduced with version `5.1.25` (https://github.com/illuminate/support/compare/v5.1.22...v5.1.25#diff-1e8872816965b849501b2e14e8727203R480). Any chance you can update your patch version of your `laravel/laravel`dependency to at least that and try again?

**Comment by Prijink** [comment]
Thank you for quick response. I'm not sure that updating Laravel

**Comment by ksassnowski** [comment]
I'm afraid there is nothing to fix in this project. 

I would seriously advice you to update your `laravel` dependency since you might be missing out on backported security fixes. You're not supposed to go from `5.1` to `5.2` but to use the latest version of the `5.1` LTS release which as of right now is `5.1.46` (https://github.com/laravel/framework/commit/7f2f892e62163138121e8210b92b21394fda8d1c). `5.1.19` is almost 2 years old by now (https://github.com/laravel/framework/commit/45e181369991579dc3ad015665eabbb72c0fadba).
