### ISSUE TITLE
Prefix for custom routes

### ISSUE THREAD

**Issue by SvaRgoS** [Dionera/laravel-beanstalkd-admin-ui#7]
Hi. I need ability to customize routes.
I have made changes but i can`t create pull request into your repository.
Did you grant access rights for create pull request?
Can you help me?
With best regards, Yury

**Comment by ksassnowski** [comment]
Hey, thanks for wanting to contribute.

In order to submit a pull request you need to create a fork of this repository and commit the changes there. Then you can create a pull request from your fork into this repository. Check out the GitHub documentation on pull requests [here](https://help.github.com/articles/creating-a-pull-request/).

**Comment by SvaRgoS** [comment]
Oh, thanks. 
Now i will try.
: -)

**Comment by SvaRgoS** [comment]
Kai, yesterday I created the pull request. I want to know what the next step?
I want to use this package in my own project and i need this changes.
I can use  the my fork package for project of course. But would be march better to use your package I think.

**Comment by ksassnowski** [comment]
Hi Yury, thanks for contributing. I need to review the pull request first before merging it. Since I'm doing this in my spare time, I will not always be able to get to it immediately. As soon as I reviewed it and everythings good I will merge it.

**Comment by SvaRgoS** [comment]
> ... I will not always be able to get to it immediately. As soon as I reviewed it and everythings good I will merge it.

I understand. It`s ok. I Will be waiting for you.

**Comment by ksassnowski** [comment]
PR got merged.
